./waf --run "ThirdChallenge03 --manager=ns3::MinstrelWifiManager --outputFileName=minstrel"
./waf --run "ThirdChallenge03 --manager=ns3::AarfWifiManager --outputFileName=aarf"
./waf --run "ThirdChallenge03 --manager=ns3::OnoeWifiManager --outputFileName=onoe"
./waf --run "ThirdChallenge03 --manager=ns3::CaraWifiManager --outputFileName=cara"
./waf --run "ThirdChallenge03 --manager=ns3::RraaWifiManager --outputFileName=rraa"
